#!/usr/bin/env ruby

root = File.expand_path(File.dirname(__FILE__) + '/../')
require 'rubygems'
require 'daemons'
require root + '/lib/daemons_patch'
require root + '/lib/change_privilege'

Daemons.run_proc(
  "email_notifier", 
  :dir_mode => :normal, 
  :dir => (root + '/tmp/pids'), 
  :log_output => true, 
  :log_dir => File.join(root, 'log'),
  :backtrace => true) do

  require root + '/config/environment'

  loop do
    QueuedEmail.all.each do | each |
      each.process
    end
    sleep(5)
  end

end
