#!/usr/bin/env ruby

root = File.expand_path(File.dirname(__FILE__) + '/../')
require 'rubygems'
require 'daemons'
require root + '/lib/daemons_patch'

Daemons.run(
  File.join(root, 'script', 'rss_feed_fetcher.rb'),
  :dir_mode => :normal, :dir => (root + '/tmp/pids'),
  :log_dir => File.join(root, 'log'),
  :log_output => true,
  :backtrace => true
)
